apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgDGwwKOhXvOjbNUsRSMZAqmbipGdIyoS9U4kKpsfpNZeqgNh2wy+SM8TKsFBP4u9iZm/qelvlW4lfPbFEF0tT0ty/3VsamRvABYc3JftMV1OBs+U1IOTjiXcL/WvacS/JPyjqhnNPXoERKpOY3u/QQdxh5Rf0SNIq5TGwt0cszyHLihdx7rWYU+HGjU61Z4OQarkmaBITOfiqohpSw7ntNIX3bew/2LRv0LGCutnp6KkqM0pA09pknmdcdz7zR2g//6jU6UJrIe6hWWyzJYKgMin0y0nqWQ0kWv/AHvNolirb2ctZChhm4Dnynxdxl9fYi0EM2CVbVPTnBfhi5h1/75/BSeikskL+WTV01sFelNXH3TMhDicVOjUqgFzdAnaTp9a0eZHXH1axVJvc+P2YST7WTovzNDpvby+jozCRAWI+fx5nheUGrntkgljNEQuwY333RgQ1i4Wh+/jAmu6jk77NfNuugGr7cjBgk7eJi5oKvkYBia0Ch6eNh5kr4qk1LopizvTz5oT88lmfjcBAP6V6ZJfv6VME3uZV6/YfeSyrFKNK35xD1+fi25mx3qVGuN9sdObKGFJnlvAszueUdA4UjOVm6JXtyppv5nZGOccuCNnRuF3K7noTFQ49nC/RjOOh/Pny+lR/HVWGmvJmQufX6r+VK/rdNhAxcttbYZkyZv9PRT/1GU6DHhQPdHZgpt9VKx9A==
    user: AgBWvbby3Nc7Tl4vel3pP9/ENBm9oIOy8ZtImFeDEIJJKfxhEminEUpy3rcS27w9KXiMmciJIyubXnGgrtWt4mC26H5gkvDGl65OwivXvyjYqw0R5bC8SyBjANJBfJw1+lLPhvQJtSgdaqq/E8Fi6cAjsoAVJLK4X0gTk/DFg/KBUYJ7iP0bQglwZvpmPDO0NoisjCeL8NEuRlLUK8cKH6xzfV/3IeG/CnNtdOU9ngXcoYJDhfs0ypvaak1zbuTQAOkhWuzWkB+DgR4j8/aUMUt6xKGmsR9Bk6Z8/sklNIX2/RBpPcGzp3Z5+zqC5sVujaYeQV4wm+b3z5f9Jy0gwltV7H1rOGP2WJRbfkemKFoBXgskSkWX27w++RIcItkGvd6AgmguXKsAN/maDDLLnmWCNchciIFXZr5sXnI2RQd1+fiVnQAM9NdpQU4U7T6Tx+bIacvJVpwDQr9+OYA7VMTCFHklYTBRaiffDUtTPyzrx5Jtlzl0VO6Rl7Xd7bGFI3is+Q6XKUJrHlFFsnCktOiId6IOzpvs7F4KPYrodsh85pFSqH7IQsjUzPfpJ7jYUfE4X7FFLsQJZAcKBKq1KQ9u3WMBdmGf3e205vBUbd/bRz+WZYmBjnGgijnV4EXQa0XSdHZp48IFAy+CUA4Uz7pUhMm24Lny2Ndv1ukn6VhNvTqg56QTn1zbVU/nsDdCttcLo4d5tQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod

